name: Node.js Version Patch and Push

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  version-patch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"

      - name: Change directory to backend
        run: cd ./backend

      - name: Install dependencies
        run: npm install

      - name: Patch version
        run: npm version patch -m "Upgrade to %s due to changes"

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump version to %s"

      - name: Push changes
        run: git push
