name: Version Patch (Manual Commit)

on:
  push: {}
  pull_request: {}

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Change directory to backend
        run: cd ./backend

      - name: Patch version (dry run)
        run: npm version patch --dry-run

      - name: Confirm version update
        run: |
          echo "New version: $(npm version patch --dry-run)"
          read -r -p "Are you sure you want to update the version? (y/N) " response
          case "$response" in
            [yY][eE][sS]|[Yy]) ;;
            *) echo "Version update cancelled."; exit 1 ;;
          esac

      - name: Update version and commit
        run: npm version patch -m
