name: Update Package Version

on:
  push:
    branches:
      - main # Replace 'main' with the correct branch name if it's different

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.12.1"

      - name: Update package version
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          cd backend # Adjust the directory path if necessary
          npm version patch -m "Automatically bump version"
          git push origin main # Replace 'main' with the correct branch name
